### ISSUE TITLE
A few GUI bugs:

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync3#3]
I tested this version on the Emulator for the first time
I do not have much time currently to start looking at the code and testing  before using it for daily jobs. However, I can test the GUI and some functions from time to time if you think the version is enough stable in development for some beta/alpha testing

Here are a few bugs I found. I did not test the core functions however.

**1. Bug in item language apply translation**

The below item is set to different language than main layout:
![InkedScreenshot_1610196877_LI](https://user-images.githubusercontent.com/2428217/104092496-a312a180-5284-11eb-8abc-62afacf20f0c.jpg)
<img width="540" alt="Screenshot_1610197887" src="https://user-images.githubusercontent.com/2428217/104092497-a443ce80-5284-11eb-8831-d3a092c28447.png">

**2. NonWrapping text in dialogs**
Many dialogs have Non Wrapping Text. I do not for Chinese/Japanese, but for occidental languages, we cannot properly read a non wrapped text. It is not how it is written

![Screenshot_1610196928](https://user-images.githubusercontent.com/2428217/104092530-d05f4f80-5284-11eb-9f16-eefe125784af.png)
![InkedScreenshot_1610197216_LI](https://user-images.githubusercontent.com/2428217/104092531-d05f4f80-5284-11eb-9396-a9e3bf59a756.jpg)
![Screenshot_1610196733](https://user-images.githubusercontent.com/2428217/104092529-cf2e2280-5284-11eb-9042-3dfb20c47885.png)

**3. Menus Alignement**
The "Advanced Options" menu should be aligned with "Options" Menu and the submenus aligned back to where "Advanced Options" is now aligned (one less level of indent for the Advanced Options). That way, space and screen appearance is better adjusted (like implemented in SMBSync2)

<img width="540" alt="Screenshot_1610197579" src="https://user-images.githubusercontent.com/2428217/104092560-0c92b000-5285-11eb-9ca9-b950da6c436e.png">

Best regards

**Comment by PhilZ-cwm6** [comment]
**4. Change text size / language**
This issue is more frequent with "Chaneg text size", but also happens sometimes with language change

- change text to big font while language is manually set to english
- when back to Main SMBSync page, the "restart app" dialog is not always shown. As a result, when you exit app and launch again, the font remains on the last setting. The issue happens almost 1/2 of the time

best regards

**Comment by Sentaroh** [comment]
Thank you.

> 3. Menus Alignement

It is the same as SMBSync2.
![image](https://user-images.githubusercontent.com/4037866/104113561-36f47400-533e-11eb-9881-082de89e75bd.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
> > 1. Menus Alignement
> 
> It is the same as SMBSync2.

Ah sorry yes, you're right.
I changed font size and it gave me a different optical impression

After all it is ok as it is now for that part

Best regards

**Comment by PhilZ-cwm6** [comment]
> **4. Change text size / language**
> This issue is more frequent with "Chaneg text size", but also happens sometimes with language change

Issues 1, 2 and 3 are fixed, thank you
Issue 4: Language chaneg seems to work properly. Text size change still no

Reproduce:
- change font from 100% to 160%
- back to main menu and exit app (no restart dialog is shown by the way)
- start again app, font is properly set at 160%
- enter settings and change back font size to 100%
- back to main menu, no restart app menu is displayed
- exit app with back button.
- **Restart app: main menu is still at 160%**
- **enter settings menu, it is at 100%**
- **back to main menu: it is now at 100%**

Best regards

**Comment by Sentaroh** [comment]
Thank you.

I fixed it.
https://github.com/Sentaroh/SMBSync3/commit/e44a40ccf6cf9dbf85d1da9436799f8381fc9572

Best regards.

**Comment by PhilZ-cwm6** [comment]
They are fixed now
The GUI seems really sleek 👍 

If I have time (not before a few months probably), I will look more closer to the core sync code (filters and sync) to check for eventual bugs and let you know.

Best regards
